#!/usr/bin/node
// this script prints the number of movies where the
// character “Wedge Antilles” is present.

const request = require('request');
request.get(process.argv[2], (err, response, body) => {
	if(err){
		console.log(err);
	} else {
		let counter = 0;
		for(const result of JSON.parse(body).results){
			for(const movie of result.characters){
				if(movie.includes('18'){
					counter++;
				}
			}
		}
	}
});
